source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!


target 'CFWebView_Example' do
  pod 'CFWebView', :path => '../'

  target 'CFWebView_Tests' do
    inherit! :search_paths

    
  end
end
